theme: minima
title: Go
author: theChad
email: theChad@users.noreply.github.com
description: > # this means to ignore newlines until "baseurl:"
  Simple browser-based, local implemntation of go. Baduk. Weiqi.
# social links
github_username:  theChad # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
